name: example
description: Flutter_rxdart_hooks package example.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_rxdart_hooks:
    path: ../

flutter:
  uses-material-design: true